// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBms8GUb2NhLcs8ofCTZrcayyjhXBqhOPo',
    appId: '1:997656751207:web:eca771f7a8b57cb8ba78c2',
    messagingSenderId: '997656751207',
    projectId: 'katsuma-auth',
    authDomain: 'katsuma-auth.firebaseapp.com',
    storageBucket: 'katsuma-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJvZGbnEwAj_A78cOr20IGUn3hVY8xMk',
    appId: '1:997656751207:android:f1d5b9116f9f29baba78c2',
    messagingSenderId: '997656751207',
    projectId: 'katsuma-auth',
    storageBucket: 'katsuma-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAot3L9ssuoFZoLHCKkuIIWTzhce9UViYI',
    appId: '1:997656751207:ios:31836b7eb0a0879eba78c2',
    messagingSenderId: '997656751207',
    projectId: 'katsuma-auth',
    storageBucket: 'katsuma-auth.appspot.com',
    iosBundleId: 'com.example.nftKatsuma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAot3L9ssuoFZoLHCKkuIIWTzhce9UViYI',
    appId: '1:997656751207:ios:7effe9d3a47a0d8dba78c2',
    messagingSenderId: '997656751207',
    projectId: 'katsuma-auth',
    storageBucket: 'katsuma-auth.appspot.com',
    iosBundleId: 'com.example.nftKatsuma.RunnerTests',
  );
}
